apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: myapp1
  name: myapp1
spec: {}

---

apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:

  labels:
    app: myphp
  name: myphp
  namespace: pipeline

spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'myapp1:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/VeerMuchandi/bgdemo.git'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'php:7.1'
        namespace: openshift
    type: Source

status:
  lastVersion: 1

