apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2020-02-28T07:13:06Z","reason":"ReadyForNewScale","message":"the
        last scale time was sufficiently old as to warrant a new scale"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2020-02-28T06:47:51Z","reason":"ValidMetricFound","message":"the
        HPA was able to successfully calculate a replica count from cpu resource utilization
        (percentage of request)"},{"type":"ScalingLimited","status":"True","lastTransitionTime":"2020-02-28T07:04:06Z","reason":"TooFewReplicas","message":"the
        desired replica count is increasing faster than the maximum scale rate"}]'
      autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":0,"currentAverageValue":"0"}}]'
    creationTimestamp: 2020-02-28T06:47:21Z
    name: hpa-example-pod
    namespace: hpa1
    resourceVersion: "563737"
    selfLink: /apis/autoscaling/v1/namespaces/hpa1/horizontalpodautoscalers/hpa-example-pod
    uid: 2bab868c-59f6-11ea-98da-026d5f68d8cc
  spec:
    maxReplicas: 8
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps.openshift.io/v1
      kind: DeploymentConfig
      name: hpa-example-pod
    targetCPUUtilizationPercentage: 70
  status:
    currentCPUUtilizationPercentage: 0
    currentReplicas: 1
    desiredReplicas: 1
    lastScaleTime: 2020-02-28T07:08:06Z
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
