apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: memory-autoscale
  namespace: mypod
spec:
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    name: myapp
    kind: DeploymentConfig
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        name: cpu-percent
        type: Utilization
        averageUtilization: 30
  resources:
    requests:
        cpu: 200m

